In [1]:
import pandas as pd

In [275]:
df = pd.read_csv("C:\\Users\\RUSHIKESH\\Downloads\\spaceship-titanic\\train.csv")
df

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False   
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False   
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True   
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False   
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True   
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False   
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False   
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False   
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0             0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1           109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2            43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3             0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4           303.0       70.0         151.0   565.0     2.0  Willy Santantines   
...           ...        ...           ...     ...     ...                ...   
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
0           False  
1            True  
2           False  
3           False  
4            True  
...           ...  
8688        False  
8689        False  
8690         True  
8691        False  
8692         True  

[8693 rows x 14 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   8693 non-null   object 
 1   HomePlanet    8492 non-null   object 
 2   CryoSleep     8476 non-null   object 
 3   Cabin         8494 non-null   object 
 4   Destination   8511 non-null   object 
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object 
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object 
 13  Transported   8693 non-null   bool   
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB


## EDA :-

### Converting categorical data into numerical :-


In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
label_encoder = LabelEncoder()

In [6]:
df['VIP'] = label_encoder.fit_transform(df.VIP) 
df['HomePlanet'] = label_encoder.fit_transform(df.HomePlanet) 
df['CryoSleep'] = label_encoder.fit_transform(df.CryoSleep) 
df['Transported'] = label_encoder.fit_transform(df.Transported) 
df['Destination'] = label_encoder.fit_transform(df.Destination) 

In [7]:
df.head()

PassengerId  HomePlanet  CryoSleep  Cabin  Destination   Age  VIP  \
0     0001_01           1          0  B/0/P            2  39.0    0   
1     0002_01           0          0  F/0/S            2  24.0    0   
2     0003_01           1          0  A/0/S            2  58.0    1   
3     0003_02           1          0  A/0/S            2  33.0    0   
4     0004_01           0          0  F/1/S            2  16.0    0   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0            0  
1            1  
2            0  
3            0  
4            1

In [8]:
df.drop(["PassengerId","Cabin","Name"], axis=1, inplace=True)

In [276]:
df['VIP'].value_counts()

False    8291
True      199
Name: VIP, dtype: int64

In [9]:
df

HomePlanet  CryoSleep  Destination   Age  VIP  RoomService  FoodCourt  \
0              1          0            2  39.0    0          0.0        0.0   
1              0          0            2  24.0    0        109.0        9.0   
2              1          0            2  58.0    1         43.0     3576.0   
3              1          0            2  33.0    0          0.0     1283.0   
4              0          0            2  16.0    0        303.0       70.0   
...          ...        ...          ...   ...  ...          ...        ...   
8688           1          0            0  41.0    1          0.0     6819.0   
8689           0          1            1  18.0    0          0.0        0.0   
8690           0          0            2  26.0    0          0.0        0.0   
8691           1          0            0  32.0    0          0.0     1049.0   
8692           1          0            2  44.0    0        126.0     4688.0   

      ShoppingMall     Spa  VRDeck  Transported  
0              0.0     0.0     0.0            0  
1             25.0   549.0    44.0            1  
2              0.0  6715.0    49.0            0  
3            371.0  3329.0   193.0            0  
4            151.0   565.0     2.0            1  
...            ...     ...     ...          ...  
8688           0.0  1643.0    74.0            0  
8689           0.0     0.0     0.0            0  
8690        1872.0     1.0     0.0            1  
8691           0.0   353.0  3235.0            0  
8692           0.0     0.0    12.0            1  

[8693 rows x 11 columns]

### Dropping null values :-

In [10]:
df.isnull().sum()

HomePlanet        0
CryoSleep         0
Destination       0
Age             179
VIP               0
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Transported       0
dtype: int64

In [11]:
data = df.dropna()
data.isnull().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Transported     0
dtype: int64

In [12]:
data.reset_index(drop=True, inplace=True)

In [13]:
data

HomePlanet  CryoSleep  Destination   Age  VIP  RoomService  FoodCourt  \
0              1          0            2  39.0    0          0.0        0.0   
1              0          0            2  24.0    0        109.0        9.0   
2              1          0            2  58.0    1         43.0     3576.0   
3              1          0            2  33.0    0          0.0     1283.0   
4              0          0            2  16.0    0        303.0       70.0   
...          ...        ...          ...   ...  ...          ...        ...   
7615           1          0            0  41.0    1          0.0     6819.0   
7616           0          1            1  18.0    0          0.0        0.0   
7617           0          0            2  26.0    0          0.0        0.0   
7618           1          0            0  32.0    0          0.0     1049.0   
7619           1          0            2  44.0    0        126.0     4688.0   

      ShoppingMall     Spa  VRDeck  Transported  
0              0.0     0.0     0.0            0  
1             25.0   549.0    44.0            1  
2              0.0  6715.0    49.0            0  
3            371.0  3329.0   193.0            0  
4            151.0   565.0     2.0            1  
...            ...     ...     ...          ...  
7615           0.0  1643.0    74.0            0  
7616           0.0     0.0     0.0            0  
7617        1872.0     1.0     0.0            1  
7618           0.0   353.0  3235.0            0  
7619           0.0     0.0    12.0            1  

[7620 rows x 11 columns]

### Dividing our data into train and test :-

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X = data.iloc[:,:-1]
Y = data.iloc[:,-1]

In [16]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.25)

## ||--Model Building--||

### 1. Logistic Regression :-

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
model_1 = LogisticRegression()

In [19]:
model_1.fit(x_train,y_train)

C:\Program Files\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
pred_logi = model_1.predict(x_test)

In [21]:
data_f = pd.DataFrame({"Actual":y_test,
                       "Predict":pred_logi})
data_f

Actual  Predict
1350       1        1
873        0        1
4969       0        1
5412       1        1
79         1        1
...      ...      ...
848        0        0
1163       0        0
6342       0        0
1622       0        0
5959       0        0

[1905 rows x 2 columns]

### Evaluating the model :-

In [193]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [194]:
cm_1 = confusion_matrix(y_test, pred_logi)
cm_1

array([[698, 256],
       [166, 785]], dtype=int64)

In [195]:
def f1_score (cm):
    TP = cm[1,1]
    TN = cm[0,0]
    FP = cm[0,1]
    FN = cm[1,0]
    
    sensitivity = TP/(TP+TN)
    precision = TP/(TP+FP)
    
    f1_score = (2*sensitivity*precision)/(sensitivity+precision)
    
    return f1_score
    

In [196]:
f1_score_logi = f1_score(cm_1)
f1_score_logi

0.62202852614897

In [197]:
accuracy_logi = accuracy_score(y_test,pred_logi )*100
accuracy_logi

77.8477690288714

### 2. Decision Tree :-

In [198]:
from sklearn.tree import DecisionTreeClassifier

In [199]:
model_2 = DecisionTreeClassifier(criterion='entropy')

In [200]:
model_2.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [201]:
pred_decis = model_2.predict(x_test)

In [202]:
cm_2 = confusion_matrix(y_test, pred_decis)
cm_2

array([[700, 254],
       [222, 729]], dtype=int64)

In [203]:
f1_score_decis = f1_score(cm_2)
f1_score_decis

0.6044776119402986

In [204]:
accuracy_decis = accuracy_score(y_test, pred_decis)*100
accuracy_decis

75.01312335958005

### 3. K-Nearest Neighbour :-

In [205]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np

In [206]:
k_values = np.array(range(3,40,2))

param_grid = dict(n_neighbors=k_values)
param_grid

{'n_neighbors': array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39])}

In [207]:
model = KNeighborsClassifier()

model_knn = GridSearchCV(estimator = model, param_grid=param_grid)

In [208]:
model_knn.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39])})

In [209]:
print(model_knn.best_score_)
print(model_knn.best_params_)

0.7914260717410324
{'n_neighbors': 37}


In [210]:
pred_knn = model_knn.predict(x_test)

In [211]:
cm_3 = confusion_matrix(y_test, pred_knn)
cm_3

array([[697, 257],
       [148, 803]], dtype=int64)

In [212]:
f1_score_knn = f1_score(cm_3)
f1_score_knn

0.62734375

In [214]:
accuracy_knn = accuracy_score(y_test, pred_knn)*100
accuracy_knn

78.74015748031496

### 4. Bagging Ensemble Technique :-  

In [43]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier

In [44]:
num_trees = np.array([100,150,200,250,300,400])

param_grid = dict(n_estimators=num_trees, base_estimator = [(DecisionTreeClassifier() )])
param_grid

{'n_estimators': array([100, 150, 200, 250, 300, 400]),
 'base_estimator': [DecisionTreeClassifier()]}

In [45]:
base_model = DecisionTreeClassifier()
bagg_model = BaggingClassifier()

model_bagg = GridSearchCV(estimator = bagg_model,
                           param_grid=param_grid)

In [46]:
model_bagg.fit(x_train, y_train)

GridSearchCV(estimator=BaggingClassifier(),
             param_grid={'base_estimator': [DecisionTreeClassifier()],
                         'n_estimators': array([100, 150, 200, 250, 300, 400])})

In [47]:
print(model_bagg.best_score_)
print(model_bagg.best_params_)

0.7886264216972879
{'base_estimator': DecisionTreeClassifier(), 'n_estimators': 400}


In [48]:
pred_bagg = model_bagg.predict(x_test)

In [49]:
cm_4 = confusion_matrix(y_test, pred_bagg)
cm_4

array([[756, 198],
       [222, 729]], dtype=int64)

In [50]:
fl_score_bagg = f1_score(cm_4)
fl_score_bagg

0.6044776119402985

In [215]:
accuracy_bagg = accuracy_score(y_test,pred_bagg)*100
accuracy_bagg

77.95275590551181

### 5. Random Forest Technique :-

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
num_trees = np.array([100,200,300])
max_features = np.array([3,5,6])

param_grid = dict(max_features = max_features, n_estimators = num_trees)
param_grid

{'max_features': array([3, 5, 6]), 'n_estimators': array([100, 200, 300])}

In [54]:
model = RandomForestClassifier()

model_randf = GridSearchCV(estimator=model, param_grid=param_grid)

In [55]:
model_randf.fit(x_train, y_train)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'max_features': array([3, 5, 6]),
                         'n_estimators': array([100, 200, 300])})

In [56]:
print(model_randf.best_score_)
print(model_randf.best_params_)

0.7921259842519686
{'max_features': 5, 'n_estimators': 200}


In [57]:
pred_randf = model_randf.predict(x_test)

In [58]:
cm_5 = confusion_matrix(y_test, pred_randf)
cm_5

array([[765, 189],
       [221, 730]], dtype=int64)

In [59]:
f1_score_randf = f1_score(cm_5)
f1_score_randf

0.6048053024026512

In [216]:
accuracy_randf = accuracy_score(y_test, pred_randf)*100
accuracy_randf

78.4776902887139

### 6. Boosting Ensemble Technique :-

In [61]:
from sklearn.ensemble import AdaBoostClassifier

In [62]:
model = AdaBoostClassifier()

In [63]:
num_trees = np.array([100,200,300])
max_features = np.array([3,5,6])

param_grid = dict( n_estimators = num_trees)
param_grid

{'n_estimators': array([100, 200, 300])}

In [64]:
model_addB= GridSearchCV(estimator=model, param_grid=param_grid)
model_addB.fit(x_train, y_train)

GridSearchCV(estimator=AdaBoostClassifier(),
             param_grid={'n_estimators': array([100, 200, 300])})

In [65]:
print(model_addB.best_score_)
print(model_addB.best_params_)

0.7877515310586177
{'n_estimators': 200}


In [66]:
pred_addB = model_addB.predict(x_test)

In [67]:
cm_6 = confusion_matrix(y_test, pred_addB)
cm_6

array([[722, 232],
       [194, 757]], dtype=int64)

In [218]:
f1_score_addB = f1_score(cm_6)
f1_score_addB

0.6134521880064829

In [69]:
accuracy_addB = accuracy_score(y_test, pred_addB)*100
accuracy_addB

77.63779527559055

### 7. Support Vector Machine (SVM) :-

In [70]:
from sklearn.svm import SVC 

In [71]:
model = SVC()

In [72]:
gamma = np.array([50 ,10,5, 0.5, 0.1, 0.05])
C = np.array([15,10,20,13,5,8,0.1, 0.05])

param_grid = dict(gamma=gamma, C=C)
param_grid

{'gamma': array([50.  , 10.  ,  5.  ,  0.5 ,  0.1 ,  0.05]),
 'C': array([15.  , 10.  , 20.  , 13.  ,  5.  ,  8.  ,  0.1 ,  0.05])}

In [73]:
model_svm = GridSearchCV(model, param_grid=param_grid)

In [107]:
model_svm.fit(x_train, y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'C': array([15.  , 10.  , 20.  , 13.  ,  5.  ,  8.  ,  0.1 ,  0.05]),
                         'gamma': array([50.  , 10.  ,  5.  ,  0.5 ,  0.1 ,  0.05])})

In [108]:
model.get_params().keys()

dict_keys(['C', 'break_ties', 'cache_size', 'class_weight', 'coef0', 'decision_function_shape', 'degree', 'gamma', 'kernel', 'max_iter', 'probability', 'random_state', 'shrinking', 'tol', 'verbose'])

In [109]:
print(model_svm.best_score_)
print(model_svm.best_params_)

0.7370078740157481
{'C': 5.0, 'gamma': 0.05}


In [110]:
pred_svm = model_svm.predict(x_test)

In [111]:
cm_7 = confusion_matrix(y_test, pred_svm)
cm_7

array([[800, 154],
       [351, 600]], dtype=int64)

In [244]:
TP = cm_7[1,1]
TN = cm_7[0,0]
FP = cm_7[0,1]
FN = cm_7[1,0]

sensitivity = TP/(TP+TN)
precision = TP/(TP+FP)
    
f1_score_svm = (2*sensitivity*precision)/(sensitivity+precision)
f1_score_svm

0.5571030640668523

In [191]:
TP = cm_7[1,1]
TN = cm_7[0,0]
FP = cm_7[0,1]
FN = cm_7[1,0]

accuracy_svm = (TP+TN)/(TP+TN+FP+FN)*100
accuracy_svm

73.49081364829397

### 8. Extreme Gradient Boosting :-

In [136]:
from xgboost import XGBClassifier

In [184]:
model_xgbm = XGBClassifier(n_estimators=100, max_depth=4)

In [186]:
model_xgbm.fit(x_train, y_train)

C:\Users\RUSHIKESH\AppData\Roaming\Python\Python38\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[13:15:13] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=4, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=12,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [187]:
pred_xgbm = model_xgbm.predict(x_test)

In [188]:
cm_8 = confusion_matrix(y_test, pred_xgbm)
cm_8

array([[733, 221],
       [174, 777]], dtype=int64)

In [245]:
TP = cm_8[1,1]
TN = cm_8[0,0]
FP = cm_8[0,1]
FN = cm_8[1,0]

sensitivity = TP/(TP+TN)
precision = TP/(TP+FP)
    
f1_score_xgbm = (2*sensitivity*precision)/(sensitivity+precision)
f1_score_xgbm

0.6196172248803828

In [246]:
accuracy_xgbm = (TP+TN)/(TP+TN+FP+FN)*100
accuracy_xgbm

79.26509186351706

In [247]:
data = {'Models':["Logistic Regression","Decision Tree","K-Nearest Neighbour",
                        "Bagging Ensemble Technique"," Random Forest Technique","Boosting Ensemble Technique",
                        "Support Vector Machine (SVM)","Extreme Gradient Boosting"],
       'F1_score': [f1_score_logi,f1_score_decis,f1_score_knn,fl_score_bagg,
                           f1_score_randf,f1_score_addB,f1_score_svm,f1_score_xgbm],
       'Accuracy' : [accuracy_logi,accuracy_decis,accuracy_knn,accuracy_bagg,
                           accuracy_randf,accuracy_addB,accuracy_svm,accuracy_xgbm]}

DF = pd.DataFrame(data)


In [248]:
DF.sort_values('Accuracy', ascending = False)

Models  F1_score   Accuracy
7     Extreme Gradient Boosting  0.619617  79.265092
2           K-Nearest Neighbour  0.627344  78.740157
4       Random Forest Technique  0.604805  78.477690
3    Bagging Ensemble Technique  0.604478  77.952756
0           Logistic Regression  0.622029  77.847769
5   Boosting Ensemble Technique  0.613452  77.637795
1                 Decision Tree  0.604478  75.013123
6  Support Vector Machine (SVM)  0.557103  73.490814

### "As we can see The highest accuracy is given to us by "Extreme Gardient Boosing" model so we decided to          go with that model."

In [251]:
test_data = pd.read_csv("C:\\Users\\RUSHIKESH\\Downloads\\spaceship-titanic\\test.csv")
test_data

PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0013_01      Earth      True     G/3/S    TRAPPIST-1e  27.0  False   
1        0018_01      Earth     False     F/4/S    TRAPPIST-1e  19.0  False   
2        0019_01     Europa      True     C/0/S    55 Cancri e  31.0  False   
3        0021_01     Europa     False     C/1/S    TRAPPIST-1e  38.0  False   
4        0023_01      Earth     False     F/5/S    TRAPPIST-1e  20.0  False   
...          ...        ...       ...       ...            ...   ...    ...   
4272     9266_02      Earth      True  G/1496/S    TRAPPIST-1e  34.0  False   
4273     9269_01      Earth     False       NaN    TRAPPIST-1e  42.0  False   
4274     9271_01       Mars      True   D/296/P    55 Cancri e   NaN  False   
4275     9273_01     Europa     False   D/297/P            NaN   NaN  False   
4276     9277_01      Earth      True  G/1498/S  PSO J318.5-22  43.0  False   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck              Name  
0             0.0        0.0           0.0     0.0     0.0   Nelly Carsoning  
1             0.0        9.0           0.0  2823.0     0.0    Lerome Peckers  
2             0.0        0.0           0.0     0.0     0.0   Sabih Unhearfus  
3             0.0     6652.0           0.0   181.0   585.0  Meratz Caltilter  
4            10.0        0.0         635.0     0.0     0.0   Brence Harperez  
...           ...        ...           ...     ...     ...               ...  
4272          0.0        0.0           0.0     0.0     0.0       Jeron Peter  
4273          0.0      847.0          17.0    10.0   144.0     Matty Scheron  
4274          0.0        0.0           0.0     0.0     0.0       Jayrin Pore  
4275          0.0     2680.0           0.0     0.0   523.0    Kitakan Conale  
4276          0.0        0.0           0.0     0.0     0.0  Lilace Leonzaley  

[4277 rows x 13 columns]

In [254]:
test_data['VIP'] = label_encoder.fit_transform(test_data.VIP) 
test_data['HomePlanet'] = label_encoder.fit_transform(test_data.HomePlanet) 
test_data['CryoSleep'] = label_encoder.fit_transform(test_data.CryoSleep) 
test_data['Destination'] = label_encoder.fit_transform(test_data.Destination) 

In [255]:
test_data.drop(["PassengerId","Cabin","Name"], axis=1, inplace=True)

In [257]:
data_test = test_data.dropna()

In [259]:
data_test.isnull().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
dtype: int64

In [260]:
data_test.reset_index(drop=True, inplace=True)

In [262]:
data_test

HomePlanet  CryoSleep  Destination   Age  VIP  RoomService  FoodCourt  \
0              0          1            2  27.0    0          0.0        0.0   
1              0          0            2  19.0    0          0.0        9.0   
2              1          1            0  31.0    0          0.0        0.0   
3              1          0            2  38.0    0          0.0     6652.0   
4              0          0            2  20.0    0         10.0        0.0   
...          ...        ...          ...   ...  ...          ...        ...   
3735           2          0            2  43.0    0         47.0        0.0   
3736           0          0            2  40.0    0          0.0      865.0   
3737           0          1            2  34.0    0          0.0        0.0   
3738           0          0            2  42.0    0          0.0      847.0   
3739           0          1            1  43.0    0          0.0        0.0   

      ShoppingMall     Spa  VRDeck  
0              0.0     0.0     0.0  
1              0.0  2823.0     0.0  
2              0.0     0.0     0.0  
3              0.0   181.0   585.0  
4            635.0     0.0     0.0  
...            ...     ...     ...  
3735        3851.0     0.0     0.0  
3736           0.0     3.0     0.0  
3737           0.0     0.0     0.0  
3738          17.0    10.0   144.0  
3739           0.0     0.0     0.0  

[3740 rows x 10 columns]

In [263]:
Final_model = XGBClassifier(n_estimators=100, max_depth=4)

In [265]:
Final_model.fit(x_train, y_train)

C:\Users\RUSHIKESH\AppData\Roaming\Python\Python38\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[13:45:33] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=4, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=12,
              num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [268]:
prediction = Final_model.predict(data_test)